// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwvtXfd35RoduXgzDIjhHBJj4p8CJYYE',
    appId: '1:108800125068:web:7fb0708c764a0a79b4f3a9',
    messagingSenderId: '108800125068',
    projectId: 'flutter-crud-990cd',
    authDomain: 'flutter-crud-990cd.firebaseapp.com',
    storageBucket: 'flutter-crud-990cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRiHFKo09bzp4XWj3mntg7Ox9fY2LGaE',
    appId: '1:108800125068:android:e6817acd7fbe350cb4f3a9',
    messagingSenderId: '108800125068',
    projectId: 'flutter-crud-990cd',
    storageBucket: 'flutter-crud-990cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHyq3w_06rdBLV4XMHTh1i7-x2yO85jA',
    appId: '1:108800125068:ios:1bebea1c492f5fddb4f3a9',
    messagingSenderId: '108800125068',
    projectId: 'flutter-crud-990cd',
    storageBucket: 'flutter-crud-990cd.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHyq3w_06rdBLV4XMHTh1i7-x2yO85jA',
    appId: '1:108800125068:ios:1bebea1c492f5fddb4f3a9',
    messagingSenderId: '108800125068',
    projectId: 'flutter-crud-990cd',
    storageBucket: 'flutter-crud-990cd.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqwvtXfd35RoduXgzDIjhHBJj4p8CJYYE',
    appId: '1:108800125068:web:d3603812eea72fb9b4f3a9',
    messagingSenderId: '108800125068',
    projectId: 'flutter-crud-990cd',
    authDomain: 'flutter-crud-990cd.firebaseapp.com',
    storageBucket: 'flutter-crud-990cd.appspot.com',
  );
}
